package com.controllers.core;

import autogenerated.objrepo.*;

public class MobileController extends APIController {

    public static Rh tRhApp() { return new Rh();}

    public static Sc tScApp() { return new Sc();}
}