package com.controllers.core;

import autogenerated.objrepo.*;
public class WebController extends APIController {

    public static Rhweb tRhWeb() { return new Rhweb();}

    public static Scweb tScWeb() { return new Scweb();}
}